language: objective-c
osx_image: xcode8.3
sudo: required

env:
  global:
    - PROJECT="TabNavigatable.xcodeproj"
    - SCHEME="TabNavigatable"
    - IOS_SDK="iphonesimulator10.3"
    - FRAMEWORK="TabNavigatable"
  matrix:
    - SDK="$IOS_SDK"	DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.3.1"

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift --version

before_script:
  - set -o pipefail
  - swift package generate-xcodeproj

script:
  - xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success: 
  - bash <(curl -s https://codecov.io/bash) -J 'TabNavigatable'

